runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: app.app
- url: /.well-known
  static_dir: .well-known

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.git*$
- ^(.*/)?\.gitignore*$
